### ISSUE TITLE
Internal error has occurred

### ISSUE THREAD

**Issue by master3395** [NeverBehave/rc_hcaptcha#2]
Hello, every time i try to use this plugin, I get the error shown below, and it redirects me back to the login page.
I am using Cloudflare.

![bilde](https://user-images.githubusercontent.com/4199669/162741506-921a6302-032b-45c7-8c1b-46ab1cabf6ca.png)

**Comment by skibbipl** [comment]
Yup, same here:
```
[19-Apr-2022 17:28:32 Europe/Berlin] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /var/www/html/roundcube/vendor/neverbehave/hcaptcha/src/HcaptchaResponse.php:17
Stack trace:
#0 /var/www/html/roundcube/vendor/neverbehave/hcaptcha/src/Hcaptcha.php(48): neverbehave\HcaptchaResponse->__construct()
#1 /var/www/html/roundcube/plugins/rc_hcaptcha/rc_hcaptcha.php(47): neverbehave\Hcaptcha->challenge()
#2 /var/www/html/roundcube/program/lib/Roundcube/rcube_plugin_api.php(513): rc_hcaptcha->authenticate()
#3 /var/www/html/roundcube/index.php(114): rcube_plugin_api->exec_hook()
#4 {main}
  thrown in /var/www/html/roundcube/vendor/neverbehave/hcaptcha/src/HcaptchaResponse.php on line 17
```
I use php 8.1:
```
php -v
PHP 8.1.2 (cli) (built: Mar 13 2022 20:36:42) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
```

**Comment by reecehill** [comment]
To fix, the following change must be made:

> Edit - /vendor/neverbehave/hcaptcha/src/HcaptchaResponse.php (Line 17)

Change
`$this->errors = $response['error-codes'];`
to
`$this->errors = $response->{'error-codes'};`
